general {
	col.active_border = rgba({{colors.primary.default.hex_stripped}}00) rgba({{colors.primary.default.hex_stripped}}00) rgba({{colors.primary.default.hex_stripped}}FF) rgba({{colors.primary.default.hex_stripped}}00) rgba({{colors.primary.default.hex_stripped}}00) rgba({{colors.tertiary.default.hex_stripped}}FF)
  col.inactive_border = rgba({{colors.outline_variant.default.hex_stripped}}88)
}

group {
	col.border_active = rgba({{colors.tertiary.default.hex_stripped}}FF) rgba({{colors.tertiary.default.hex_stripped}}FF) rgba({{colors.tertiary.default.hex_stripped}}FF) rgba({{colors.background.default.hex_stripped}}FF) rgba({{colors.tertiary.default.hex_stripped}}FF) 

  col.border_inactive = rgba({{colors.tertiary.default.hex_stripped}}66) rgba({{colors.background.default.hex_stripped}}FF) rgba({{colors.tertiary.default.hex_stripped}}66) rgba({{colors.background.default.hex_stripped}}FF)

	col.border_locked_active = rgba({{colors.tertiary.default.hex_stripped}}88) rgba({{colors.tertiary.default.hex_stripped}}FF) rgba({{colors.faded_red.default.hex_stripped}}FF) rgba({{colors.tertiary.default.hex_stripped}}FF)

  col.border_locked_inactive = rgba({{colors.neutral_red.default.hex_stripped}}66) rgba({{colors.background.default.hex_stripped}}FF) rgba({{colors.neutral_red.default.hex_stripped}}66) rgba({{colors.background.default.hex_stripped}}FF)


	groupbar {
		gradients = true
		gradient_rounding = 4
		text_color = rgba({{colors.on_primary.default.hex_stripped}}FF)
		stacked = false
		
		col.active = rgba({{colors.tertiary.default.hex_stripped}}FF) 
   	col.inactive = rgba({{colors.tertiary.default.hex_stripped}}88)
		col.locked_active = rgba({{colors.tertiary.default.hex_stripped}}FF) 
   	col.locked_inactive = rgba({{colors.tertiary.default.hex_stripped}}88)

	}
}



misc {
    background_color = rgba({{colors.surface.dark.hex_stripped}}FF)
}

decoration {
    shadow {
        color = rgba({{colors.secondary.default.hex_stripped}}CC)
        color_inactive = rgba({{colors.background.default.hex_stripped}}00)
    }
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba({{colors.background.default.hex_stripped}}FF)
        col.text = rgba({{colors.on_background.default.hex_stripped}}FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb({{colors.on_background.default.hex_stripped}}), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb({{colors.on_background.default.hex_stripped}}), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb({{colors.on_background.default.hex_stripped}}), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba({{colors.primary.default.hex_stripped}}AA) rgba({{colors.primary.default.hex_stripped}}77),pinned:1
