[config]
version_check = false

[config.custom_colors]
extra_onSuccess_dark = '#213528'
extra_successContainer_dark = '#374B3E'
extra_onSuccessContainer_dark = '#D1E9D6'
extra_success_light = '#4F6354'
extra_onSuccess_light = '#FFFFFF'
extra_successContainer_light = '#D1E8D5'
extra_onSuccessContainer_light = '#0C1F13'
term0_dark = "#282828"
term1_dark = "#CC241D"
term2_dark = "#98971A"
term3_dark = "#D79921"
term4_dark = "#458588"
term5_dark = "#B16286"
term6_dark = "#689D6A"
term7_dark = "#A89984"
term8_dark = "#928374"
term9_dark = "#FB4934"
term10_dark = "#B8BB26"
term11_dark = "#FABD2F"
term12_dark = "#83A598"
term13_dark = "#D3869B"
term14_dark = "#8EC07C"
term15_dark = "#EBDBB2"
term0_light = "#FDF9F3"
term1_light = "#FF6188"
term2_light = "#A9DC76"
term3_light = "#FC9867"
term4_light = "#FFD866"
term5_light = "#F47FD4"
term6_light = "#78DCE8"
term7_light = "#333034"
term8_light = "#121212"
term9_light = "#FF6188"
term10_light = "#A9DC76"
term11_light = "#FC9867"
term12_light = "#FFD866"
term13_light = "#F47FD4"
term14_light = "#78DCE8"
term15_light = "#333034"
bright_black = "#444444"
bright_white = "#ffffff"
bright_red = "#ff3232"
bright_green = "#32ff32"
bright_yellow = "#feff32"
bright_blue = "#3232ff"
bright_purple = "#ff32fe"
bright_aqua = "#32feff"
bright_orange = "#ff9932"
neutral_black = "#000000"
neutral_white = "#f0f0f0"
neutral_red = "#d60000"
neutral_green = "#00d600"
neutral_yellow = "#d6d600"
neutral_blue = "#0000d6"
neutral_purple = "#d600d6"
neutral_aqua = "#00d6d6"
neutral_orange = "#d66b00"
faded_red = "#a80000"
faded_green = "#00a800"
faded_yellow = "#a8a800"
faded_blue = "#0000a8"
faded_purple = "#a800a8"
faded_aqua = "#00a8a8"
faded_orange = "#a85400"


[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian/theme.css'
output_path = '~/Documentos/vault/.obsidian/themes/Matugen/theme.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode/vscode-color-theme.json'
output_path = '~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json'

[templates.perplexity]
input_path = '~/.config/matugen/templates/perplexity/ppx-matugen-colors.json'
output_path = '~/.config/tampermonkey/ppx-matugen-colors.json'

[templates.nvim]
input_path = '~/.config/matugen/templates/generic/hex.lua'
output_path = '~/.config/nvim/lua/assets/matugen_colors.lua'
post_hook = 'bash ~/0/my-dotfiles/scripts/send-reload-command-to-nvim.sh'
