" -----------------------------------------------------------------------------
" Zathura Colors
" -----------------------------------------------------------------------------

" Colors
set default-bg              "rgba(19, 19, 19, 1)"
set default-fg              "#e2e2e2"

set statusbar-bg            "#003545"
set statusbar-fg            "#60d4fe"

set inputbar-bg             "#003545"
set inputbar-fg             "#60d4fe"

set notification-error-bg   "#690005"
set notification-error-fg   "#ffb4ab"

set notification-warning-bg "#baeaff"
set notification-warning-fg "#93000a"

set highlight-color         "#baeaff"
set highlight-active-color  "#60d4fe"

set completion-highlight-fg "#003545"
set completion-highlight-bg "#60d4fe"

set completion-bg           "#003545"
set completion-fg           "#60d4fe"

set notification-bg         "#003545"
set notification-fg         "#60d4fe"

set recolor                 "true"
set recolor-lightcolor      "rgba(19, 19, 19, 1)"
set recolor-darkcolor       "#b3cad5"
set recolor-reverse-video   "true"
set recolor-keephue         "true"

