" -----------------------------------------------------------------------------
" Zathura Colors
" -----------------------------------------------------------------------------

" Colors
set default-bg              "rgba(28, 17, 13, 1)"
set default-fg              "#f5ded7"

set statusbar-bg            "#003061"
set statusbar-fg            "#a7c8ff"

set inputbar-bg             "#003061"
set inputbar-fg             "#a7c8ff"

set notification-error-bg   "#690005"
set notification-error-fg   "#ffb4ab"

set notification-warning-bg "#d5e3ff"
set notification-warning-fg "#93000a"

set highlight-color         "#d5e3ff"
set highlight-active-color  "#a7c8ff"

set completion-highlight-fg "#003061"
set completion-highlight-bg "#a7c8ff"

set completion-bg           "#003061"
set completion-fg           "#a7c8ff"

set notification-bg         "#003061"
set notification-fg         "#a7c8ff"

set recolor                 "true"
set recolor-lightcolor      "rgba(28, 17, 13, 1)"
set recolor-darkcolor       "#ecbe91"
set recolor-reverse-video   "true"
set recolor-keephue         "true"

