" -----------------------------------------------------------------------------
" Zathura Colors
" -----------------------------------------------------------------------------

" Colors
set default-bg              "rgba(26, 18, 9, 0.8)"
set default-fg              "#f2dfd1"

set statusbar-bg            "#2d2767"
set statusbar-fg            "#c6c0ff"

set inputbar-bg             "#2d2767"
set inputbar-fg             "#c6c0ff"

set notification-error-bg   "#690005"
set notification-error-fg   "#ffb4ab"

set notification-warning-bg "#e4dfff"
set notification-warning-fg "#93000a"

set highlight-color         "#e4dfff"
set highlight-active-color  "#c6c0ff"

set completion-highlight-fg "#2d2767"
set completion-highlight-bg "#c6c0ff"

set completion-bg           "#2d2767"
set completion-fg           "#c6c0ff"

set notification-bg         "#2d2767"
set notification-fg         "#c6c0ff"

set recolor                 "true"
set recolor-lightcolor      "rgba(26, 18, 9, 0.8)"
set recolor-darkcolor       "#b1cfa9"
set recolor-reverse-video   "true"
set recolor-keephue         "true"

