# Matugen Hyprland Colors

$background = rgb(1d0f13)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(3c2c30)

$inverse_primary = rgb(b9045e)

$inverse_surface = rgb(f7dce1)

$on_background = rgb(f7dce1)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(650030)

$on_primary_container = rgb(000000)

$on_primary_fixed = rgb(3f001c)

$on_primary_fixed_variant = rgb(8e0047)

$on_secondary = rgb(610c30)

$on_secondary_container = rgb(ffd6df)

$on_secondary_fixed = rgb(3f001c)

$on_secondary_fixed_variant = rgb(7e2547)

$on_surface = rgb(f7dce1)

$on_surface_variant = rgb(e0bec5)

$on_tertiary = rgb(5c1a00)

$on_tertiary_container = rgb(000000)

$on_tertiary_fixed = rgb(380d00)

$on_tertiary_fixed_variant = rgb(822800)

$outline = rgb(a88990)

$outline_variant = rgb(594046)

$primary = rgb(ffb1c6)

$primary_container = rgb(fe4b91)

$primary_fixed = rgb(ffd9e1)

$primary_fixed_dim = rgb(ffb1c6)

$scrim = rgb(000000)

$secondary = rgb(ffb1c6)

$secondary_container = rgb(7e2547)

$secondary_fixed = rgb(ffd9e1)

$secondary_fixed_dim = rgb(ffb1c6)

$shadow = rgb(000000)

$source_color = rgb(de3079)

$surface = rgb(1d0f13)

$surface_bright = rgb(463539)

$surface_container = rgb(2a1b1f)

$surface_container_high = rgb(36262a)

$surface_container_highest = rgb(413034)

$surface_container_low = rgb(26181b)

$surface_container_lowest = rgb(170a0e)

$surface_dim = rgb(1d0f13)

$surface_tint = rgb(ffb1c6)

$surface_variant = rgb(594046)

$tertiary = rgb(ffb59b)

$tertiary_container = rgb(f85f1e)

$tertiary_fixed = rgb(ffdbcf)

$tertiary_fixed_dim = rgb(ffb59b)

