source = ~/0/my-dotfiles/hypr/hyprland/input.conf
source = ~/0/my-dotfiles/hypr/hyprland/monitors.conf


source = ~/0/my-dotfiles/hypr/hyprland/var_base.conf
source = ~/0/my-dotfiles/hypr/hyprland/var_exo.conf
source = ~/0/my-dotfiles/hypr/hyprland/preferences.conf

source = ~/0/my-dotfiles/hypr/hyprland/general.conf
source = ~/0/my-dotfiles/hypr/hyprland/execs.conf
source = ~/0/my-dotfiles/hypr/hyprland/rules_windows.conf
source = ~/0/my-dotfiles/hypr/hyprland/keymaps_base.conf
source = ~/0/my-dotfiles/hypr/hyprland/env.conf
source = ~/0/my-dotfiles/hypr/hyprland/hyprland.conf
