return  {
	-- colors
	red = "#ffffff",
	orange = "#ffffff",
	green = "#ffffff",
	yellow = "#ffffff",
	blue = "#ffffff",
	magenta = "#ffffff",
	cyan = "#ffffff",
	black = "#ffffff",
	bright_red = "#ffffff",
	bright_orange = "#ffffff",
	bright_green = "#ffffff",
	bright_yellow = "#ffffff",
	bright_blue = "#ffffff",
	bright_magenta = "#ffffff",
	bright_cyan = "#ffffff",
	white = "#ffffff",
	
	-- UI
	bg = "#131313",
	inactiveBg = "#474747",
	fg = "#e2e2e2",
	floatBorder = "#e2e2e2",
	line = "#1f1f1f",
	--search = "#405065",
	-- elements
	--comment = "#c6c6c6",
	--builtin = "#ffffff",
	--func = "#ffffff",
	--string = "#ffffff",
	--number = "#ffffff",
	--property = "#c3c3d5",
	--constant = "#aeaed1",
	--parameter = "#bb9dbd",
	--visual = "#ffffff",
	--error = "#ffb4ab",
	--warning = "#ffffff",
	--hint = "#ffffff",
	--operator = "#90a0b5",
	--keyword = "#e2e2e2",
	--type = "#c6c6c6",
	--plus = "#ffffff",
	--delta = "#ffffff",
}
