return  {
	-- colors
	red = "#ffb2b9",
	orange = "#ffb59b",
	green = "#43f094",
	yellow = "#ccfc5b",
	blue = "#afc6ff",
	magenta = "#eab2ff",
	cyan = "#81ebff",
	black = "#c6c6c6",
	bright_red = "#ffb2bd",
	bright_orange = "#ffbfa1",
	bright_green = "#ecffed",
	bright_yellow = "#ffffff",
	bright_blue = "#b0c6ff",
	bright_magenta = "#eab2ff",
	bright_cyan = "#ffffff",
	white = "#ffffff",
	
	-- UI
	bg = "#121315",
	inactiveBg = "#3c4853",
	fg = "#e3e2e4",
	floatBorder = "#d5e1f0",
	line = "#1e2022",

	visual_bg = "#333537",
	visual_fg = "#121315",
	--search = "#405065",


	-- elements
	comment = "#c2c7cd",
	builtin = "#ecffed",
	func = "#81ebff",
	string = "#ffbfa1",
	number = "#ffb59a",
	--property = "#c3c3d5",
	--constant = "#aeaed1",
	--parameter = "#bb9dbd",
	visual = "#b0c6ff",
	error = "#ffb4ab",
	warning = "#ccfc5b",
	hint = "#aacae9",
	operator = "#90a0b5",
	keyword = "#ecbe89",
	type = "#bcc8d6",
	plus = "#43f094",
	delta = "#ffb59b",
}
