general {
	col.active_border = rgba(9bccf800) rgba(9bccf800) rgba(9bccf8FF) rgba(9bccf800) rgba(9bccf800) rgba(f4bd72FF)
  col.inactive_border = rgba(41474e88)
}

group {
	col.border_active = rgba(f4bd72FF) rgba(f4bd72FF) rgba(f4bd72FF) rgba(111416FF) rgba(f4bd72FF) 

  col.border_inactive = rgba(f4bd7266) rgba(111416FF) rgba(f4bd7266) rgba(111416FF)

	col.border_locked_active = rgba(f4bd7288) rgba(f4bd72FF) rgba(ffb2b9FF) rgba(f4bd72FF)

  col.border_locked_inactive = rgba(ffb2b966) rgba(111416FF) rgba(ffb2b966) rgba(111416FF)


	groupbar {
		gradients = true
		gradient_rounding = 4
		text_color = rgba(003351FF)
		stacked = false
		
		col.active = rgba(f4bd72FF) 
   	col.inactive = rgba(f4bd7288)
		col.locked_active = rgba(f4bd72FF) 
   	col.locked_inactive = rgba(f4bd7288)

	}
}



misc {
    background_color = rgba(111416FF)
}

decoration {
    shadow {
        color = rgba(b6c9dcCC)
        color_inactive = rgba(11141600)
    }
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(111416FF)
        col.text = rgba(e2e2e6FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(e2e2e6), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(e2e2e6), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(e2e2e6), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(9bccf8AA) rgba(9bccf877),pinned:1
