general {
	col.active_border = rgba(aacae900) rgba(aacae900) rgba(aacae9FF) rgba(aacae900) rgba(aacae900) rgba(ecbe89FF)
  col.inactive_border = rgba(42474d88)
}

group {
	col.border_active = rgba(ecbe89FF) rgba(ecbe89FF) rgba(ecbe89FF) rgba(121315FF) rgba(ecbe89FF) 

  col.border_inactive = rgba(ecbe8966) rgba(121315FF) rgba(ecbe8966) rgba(121315FF)

	col.border_locked_active = rgba(ecbe8988) rgba(ecbe89FF) rgba(ffb2b9FF) rgba(ecbe89FF)

  col.border_locked_inactive = rgba(ffb2b966) rgba(121315FF) rgba(ffb2b966) rgba(121315FF)


	groupbar {
		gradients = true
		gradient_rounding = 4
		text_color = rgba(0f334cFF)
		stacked = false
		
		col.active = rgba(ecbe89FF) 
   	col.inactive = rgba(ecbe8988)
		col.locked_active = rgba(ecbe89FF) 
   	col.locked_inactive = rgba(ecbe8988)

	}
}



misc {
    background_color = rgba(121315FF)
}

decoration {
    shadow {
        color = rgba(bcc8d6CC)
        color_inactive = rgba(12131500)
    }
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(121315FF)
        col.text = rgba(e3e2e4FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(e3e2e4), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(e3e2e4), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(e3e2e4), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(aacae9AA) rgba(aacae977),pinned:1
