general {
	col.active_border = rgba(8cd3d300) rgba(8cd3d300) rgba(8cd3d3FF) rgba(8cd3d300) rgba(8cd3d300) rgba(ffb695FF)
  col.inactive_border = rgba(3f494888)
}

group {
	col.border_active = rgba(ffb695FF) rgba(ffb695FF) rgba(ffb695FF) rgba(101414FF) rgba(ffb695FF) 

  col.border_inactive = rgba(ffb69566) rgba(101414FF) rgba(ffb69566) rgba(101414FF)

	col.border_locked_active = rgba(ffb69588) rgba(ffb695FF) rgba(ffb596FF) rgba(ffb695FF)

  col.border_locked_inactive = rgba(ffb59666) rgba(101414FF) rgba(ffb59666) rgba(101414FF)


	groupbar {
		gradients = true
		gradient_rounding = 4
		stacked = false
		height = 8
		indicator_height = 0
		render_titles = false
		col.active = rgba(ffb695FF) 
  	col.inactive = rgba(ffb69588)
		col.locked_active = rgba(ffb695FF) 
  	col.locked_inactive = rgba(ffb69588)
		text_color = rgba(003738FF)
	}
}



misc {
    background_color = rgba(101414FF)
}

decoration {
	shadow {
			color = rgba(b1ccccCC)
			color_inactive = rgba(10141400)
	}
}

plugin {
	hyprbars {
		# Honestly idk if it works like css, but well, why not
		bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
		bar_height = 30
		bar_padding = 10
		bar_button_padding = 5
		bar_precedence_over_border = true
		bar_part_of_window = true

		bar_color = rgba(101414FF)
		col.text = rgba(e0e3e2FF)


		# example buttons (R -> L)
		# hyprbars-button = color, size, on-click
		hyprbars-button = rgb(e0e3e2), 13, 󰖭, hyprctl dispatch killactive
		hyprbars-button = rgb(e0e3e2), 13, 󰖯, hyprctl dispatch fullscreen 1
		hyprbars-button = rgb(e0e3e2), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
	}
}

windowrulev2 = bordercolor rgba(8cd3d3AA) rgba(8cd3d377),pinned:1
