group {
	col.border_active = rgba($tertiaryFF)
  col.border_inactive = rgba($background55)
	col.border_locked_active = rgba($errorFF) rgba($tertiaryFF)
  col.border_locked_inactive = rgba($errorFF) rgba($background00)


	groupbar {
		gradients = true
		gradient_rounding = 4
		stacked = false
		height = 8
		indicator_height = 0
		render_titles = false
		col.active = rgba($tertiaryCC)
  	col.inactive = rgba($background22)
		col.locked_active = rgba($tertiaryFF)
  	col.locked_inactive = rgba($background22)
		text_color = rgba($on_tertiaryFF)
	}
}
