

group {
	########col.border_active = rgba($tertiaryFF) rgba($tertiary00) 0deg
  col.border_inactive = rgba($tertiary66)
	col.border_locked_active = rgba($tertiaryFF) rgba($tertiary00) 0deg
	col.border_locked_inactive = rgba($errorFF)


	groupbar {
		gradients = true
		gradient_rounding = 10
		stacked = false
		height = 3
		indicator_height = 0
		render_titles = false
		col.active = rgba($tertiaryFF)
  	col.inactive = rgba($tertiary55)
		col.locked_active = rgba($error_containerFF)
  	col.locked_inactive = rgba($error_container55)
		text_color = rgba($on_tertiaryFF)
	}
}
