$powerMenu = ignis toggle-window PowerMenu
$settings = ignis toggle-window Setting
$inspector = ignis inspector
$recordRegion = ignis run-command recorder-record-region
$recordScreen = ignis run-command recorder-record-screen
