$screenShot = hyprshot --clipboard-only -z --mode region

$volumeOutUp = wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
$volumeOutDown = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

$volumeOutMute = wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
$volumeInMute = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

$brightnessUp = brightnessctl s 10%+
$brightnessDown = brightnessctl s 10%-

$mediaNext = playerctl next
$mediaPlayPause = playerctl play-pause
$mediaPrevious = playerctl previous
