return  {
	bg = "{{colors.background.default.hex}}",
	inactiveBg = "{{colors.secondary_container.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	floatBorder = "{{colors.on_secondary_container.default.hex}}",
	line = "{{colors.surface_container.default.hex}}",
	comment = "{{colors.on_surface_variant.default.hex}}",
	builtin = "{{colors.bright_green.default.hex}}",
	func = "{{colors.neutral_aqua.default.hex}}",
	string = "{{colors.bright_orange.default.hex}}",
	number = "{{colors.faded_orange.default.hex}}",
	property = "#c3c3d5",
	constant = "#aeaed1",
	parameter = "#bb9dbd",
	visual = "{{colors.bright_blue.default.hex}}",
	error = "{{colors.error.default.hex}}",
	warning = "{{colors.neutral_yellow.default.hex}}",
	hint = "{{colors.primary.default.hex}}",
	operator = "#90a0b5",
	keyword = "{{colors.tertiary.default.hex}}",
	type = "{{colors.secondary.default.hex}}",
	search = "#405065",
	plus = "{{colors.neutral_green.default.hex}}",
	delta = "{{colors.neutral_orange.default.hex}}",
}
