return  {
	-- colors
	red = "{{colors.neutral_red.default.hex}}",
	orange = "{{colors.neutral_orange.default.hex}}",
	green = "{{colors.neutral_green.default.hex}}",
	yellow = "{{colors.neutral_yellow.default.hex}}",
	blue = "{{colors.neutral_blue.default.hex}}",
	magenta = "{{colors.neutral_purple.default.hex}}",
	cyan = "{{colors.neutral_aqua.default.hex}}",
	black = "{{colors.neutral_black.default.hex}}",
	bright_red = "{{colors.bright_red.default.hex}}",
	bright_orange = "{{colors.bright_orange.default.hex}}",
	bright_green = "{{colors.bright_green.default.hex}}",
	bright_yellow = "{{colors.bright_yellow.default.hex}}",
	bright_blue = "{{colors.bright_blue.default.hex}}",
	bright_magenta = "{{colors.bright_purple.default.hex}}",
	bright_cyan = "{{colors.bright_aqua.default.hex}}",
	white = "{{colors.neutral_white.default.hex}}",
	
	-- UI
	bg = "{{colors.background.default.hex}}",
	inactiveBg = "{{colors.secondary_container.default.hex}}",
	fg = "{{colors.on_surface.default.hex}}",
	floatBorder = "{{colors.on_secondary_container.default.hex}}",
	line = "{{colors.surface_container.default.hex}}",
	--search = "#405065",
	-- elements
	--comment = "{{colors.on_surface_variant.default.hex}}",
	--builtin = "{{colors.bright_green.default.hex}}",
	--func = "{{colors.neutral_aqua.default.hex}}",
	--string = "{{colors.bright_orange.default.hex}}",
	--number = "{{colors.faded_orange.default.hex}}",
	--property = "#c3c3d5",
	--constant = "#aeaed1",
	--parameter = "#bb9dbd",
	--visual = "{{colors.bright_blue.default.hex}}",
	--error = "{{colors.error.default.hex}}",
	--warning = "{{colors.neutral_yellow.default.hex}}",
	--hint = "{{colors.primary.default.hex}}",
	--operator = "#90a0b5",
	--keyword = "{{colors.tertiary.default.hex}}",
	--type = "{{colors.secondary.default.hex}}",
	--plus = "{{colors.neutral_green.default.hex}}",
	--delta = "{{colors.neutral_orange.default.hex}}",
}
